name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: nixos/nix

    steps:
    - uses: actions/checkout@v4
    - run: make run-shell
    - run: ghc --make includes.hs
    - run: make
